kroma-network/kroma

packages/sdk/tasks/index.ts
packages/sdk/tasks/register-erc20.ts

Added a script to register L1's ERC20 token to WEMIX Kanvas.
After running this script, send a bridgeERC20 transaction to the L1StandardBridge contract, which will deposit ERC20 into WEMIX Kanvas.

feat(sdk): add erc20 registration script

---

specs/challenge.md

docs: update commit message format

docs: update challenge.md

---

specs/differences-from-optimism-bedrock.md

docs: update commit message format

docs: update differences-from-optimism-bedrock.md

---

specs/zkevm-prover.md

docs: update commit message format

docs: update zkevm-prover.md

---

components/batcher/batcher.go
components/batcher/cmd/main.go
components/batcher/flags/flags.go
components/batcher/metrics/metrics.go
components/node/cmd/main.go
components/node/rollup/derive/payloads_queue.go
components/validator/abi_test.go
components/validator/challenger.go
components/validator/cmd/main.go
components/validator/config.go
components/validator/flags/flags.go
components/validator/l2_output_submitter.go
components/validator/metrics/metrics.go
components/validator/metrics/noop.go
components/validator/validator.go
ops-devnet/docker-compose.yml
utils/monitoring/monitoring.go
utils/service/txmgr/cli.go
utils/service/txmgr/txmgr.go
utils/service/txmgr/txmgr_test.go

- https://github.com/ethereum-optimism/optimism/pull/5258
- https://github.com/ethereum-optimism/optimism/pull/5283
- https://github.com/ethereum-optimism/optimism/pull/5295
- https://github.com/ethereum-optimism/optimism/pull/5189
- https://github.com/ethereum-optimism/optimism/pull/5246

feat(validator): apply op-proposer v1.0.3 to Kroma

---

packages/contracts/contracts/L1/Colosseum.sol
packages/contracts/contracts/L1/ValidatorPool.sol
packages/contracts/contracts/libraries/Types.sol
packages/contracts/contracts/test/Colosseum.t.sol

- apply SafeCall in the window() of the ValidatorPool
- optimize storage slot of Types.Challenge

refac(contracts): apply SafeCall in the withdraw() of the ValidatorPool

---

packages/contracts/contracts/L1/SecurityCouncil.sol
packages/contracts/contracts/libraries/Types.sol
packages/contracts/contracts/test/CommonTest.t.sol
packages/contracts/contracts/test/SecurityCouncil.t.sol
packages/contracts/contracts/universal/IMultiSigWallet.sol
packages/contracts/contracts/universal/MultiSigWallet.sol

- add multisig base contract
- add security council contract
- add test code for security council contract
Related: #18

feat(contracts): implement security council contracts

---

specs/deposits.md
specs/glossary.md

docs: add contents about validator reward

---

specs/challenge.md
specs/zkevm-prover.md

Add more description of kroma-prover in detail.
- on zkevm-prover.md, explanation of the workflow of kroma-prover was added.
- on challenge.md, add code which calculates public input

docs: rewrite description of zkevm-prover

---

components/validator/l2_output_submitter.go
e2e/setup.go
e2e/system_test.go
e2e/system_tob_test.go

test(e2e): add validation reward test

---

components/validator/guardian.go

guardians send transactions from multiple accounts at the same time, so need more than the estimated gas limit.

feat(validator): apply gas limit multiplier to guardian transactions

---

packages/contracts/src/deploy-utils.ts

Remove the bytecode check logic because the conditional statement checking for contract changes was always comparing the same value, and the hardhat-deploy package already checks for changes.
Related: #89, 369728d

chore(contracts): remove wrong bytecode diff checking logic

---

e2e/actions/l1_miner.go
e2e/actions/l1_replica.go
e2e/actions/l1_replica_test.go
e2e/actions/l2_challenger_test.go
e2e/actions/l2_proposer.go
e2e/actions/l2_proposer_test.go
e2e/actions/l2_runtime.go
e2e/actions/l2_validator.go
e2e/actions/l2_validator_test.go
e2e/actions/user_test.go

Test code for challenger timeout in a challenge situation.
Added a check for the bond amount.

test(e2e): add challenger timeout fail test

---

specs/challenge.md
specs/differences-from-optimism-bedrock.md

Updated differences from Optimism to reflect recent implementations.

docs: update specs - differences from Optimism

---

components/validator/challenger.go
components/validator/l2_output_submitter.go
components/validator/metrics/metrics.go
components/validator/metrics/noop.go
components/validator/validator.go
e2e/actions/l2_validator.go
utils/service/metrics/balance.go
utils/service/metrics/balance_test.go

Added metric
1. The deposit amount into the ValidatorPool contract.
2. The address of the next validator.
3. The output index that the challenge function last checked.
**If there's a metric you need, feel free to leave it in the issue.**

feat(validator): add validator metrics

---

.github/ISSUE_TEMPLATE/issue_template.yaml

chore: revise issue template

---

e2e/actions/l2_challenger_test.go
e2e/e2eutils/setup.go

Add e2e test about challenge timeout fail case.

test(e2e): add challenge timeout fail case

---

LICENSE
components/node/LICENSE
packages/common-ts/LICENSE
packages/contracts/LICENSE
packages/core-utils/LICENSE
packages/hardhat-deploy-config/LICENSE
packages/sdk/LICENSE

Apply the contents of PR #131 to the `dev` branch.
It must use the rebase and merge strategy.

chore: apply license hotfix

---

components/validator/challenger.go

Related to https://github.com/chainlight-io/2023-kroma-network-audit-issues-client/issues/11 reported by theori audit.
L1 reorg was not taken into account in the challenger before.
If L1 reorg occurs, the challenger verifies the newly generated output checkpoint.

feat(validator): handle the output when L1 reorg occurs

---

components/node/rollup/derive/validator_reward.go
e2e/system_test.go

Changed temp validator reward ratio to 1.

feat(validator): change validator reward scalar to 1

---

.github/workflows/ci.yml
.github/workflows/test.yml

Increases resources to speed up testing and builds

ci: change ci machine

---

components/validator/challenge/fetcher.go

There was an error in parsing jsonRPC response.

fix: fix parse of jsonRPC response from prover

---

packages/contracts/tasks/forge-verify.ts

forge verify-contract script didn't work when foundry version changed, fixed to work on new foundry version.
tested foundry release tag: d369d24

fix(contracts): modify the forge-verify script for the new foundry version

---

components/validator/challenger.go

Added output index and challenger address to challenger logs when crafting colosseum tx.

chore(validator): add detailed info of challenge

---

components/validator/challenger.go

When handling challenge as a challenger, if output is already deleted by another challenger, prevent unnecessary proving fault. This is because unlike bisecting, proving fault is a process that involves expensive computation.

feat(validator): prevent proving fault when output is already deleted

---

components/batcher/metrics/metrics.go

Add a metric to track the "batch-compression-ratio" value.

feat(batcher): add ChannelComprRatioValue metrics

---

e2e/e2eutils/setup.go
e2e/setup.go
packages/contracts/deploy-config/devnetL1.json
packages/contracts/deploy-config/sepolia.json
packages/contracts/deploy/014-TimeLock.ts
packages/contracts/deploy/015-UpgradeGovernor.ts
utils/chain-ops/genesis/config.go
utils/chain-ops/genesis/layer_one.go
utils/chain-ops/genesis/testdata/test-deploy-config-full.json

The governor configuration settings have been renamed to better group and objectify them.

chore: renaming configuration values in governor

---

components/batcher/batcher.go
components/batcher/cmd/main.go
components/batcher/config.go
components/batcher/flags/flags.go
components/batcher/rpc/config.go
components/node/cmd/batch_decoder/main.go
components/node/cmd/main.go
components/node/flags/flags.go
components/node/flags/p2p_flags.go
components/validator/cmd/balance/cmd.go
components/validator/cmd/main.go
components/validator/config.go
components/validator/flags/flags.go
components/validator/validator.go
go.mod
go.sum
utils/service/log/cli.go
utils/service/metrics/cli.go
utils/service/pprof/cli.go
utils/service/rpc/cli.go
utils/service/tls/cli.go
utils/service/txmgr/cli.go
utils/service/util.go
utils/signer/client/config.go

Migrate all v1 code in the urfave-cli to v2.

chore: upgrade urfave-cli v1 to v2

---

packages/contracts/deploy/L2/100-Proxies.ts
packages/contracts/deploy/L2/101-SecurityCouncilToken.ts
packages/contracts/deploy/L2/102-TimeLock.ts
packages/contracts/deploy/L2/103-UpgradeGovernor.ts
packages/contracts/deploy/L2/999-TransferOwnerships.ts

Add L2 governance contracts.
- SecurityCouncilToken.sol
- TimeLock.sol
- UpgradeGovernor.sol

feat(contracts): add L2 governance contracts

---

components/validator/challenger.go
components/validator/guardian.go
components/validator/l2_output_submitter.go
components/validator/validator.go
e2e/actions/l2_validator.go
utils/service/watcher/contract.go

When the contract is upgraded, the value of the contract used by each component should be updated. Therefore, when a contract upgrade event occurs, it reads back the value of that contract and changes the config.

feat: update config automatically

---

packages/contracts/deploy-config/mainnet.json

Change timelock delay from 30 to 7 days (mainnet).

chore: change timelock delay

---

packages/contracts/deploy-config/mainnet.json
packages/contracts/deploy-config/sepolia.json
packages/contracts/deploy/L2/102-TimeLock.ts
packages/contracts/src/deploy-config.ts
utils/chain-ops/genesis/config.go
utils/chain-ops/genesis/testdata/test-deploy-config-full.json

Add timeLock deploy config for l2 protocol governance.
Deploy l2 protocol governance timelock deploy for 7 days.

chore: add timeLock deploy config for l2 protocol governance

---

packages/contracts/contracts/L1/AssetManager.sol
packages/contracts/contracts/libraries/Atan2.sol
packages/contracts/contracts/libraries/BalancedWeightTree.sol
packages/contracts/contracts/libraries/Uint128Math.sol
packages/contracts/contracts/test/AssetManager.t.sol
packages/contracts/contracts/test/BalancedWeightTree.t.sol
packages/contracts/contracts/universal/IKGHManager.sol
packages/contracts/src/contract-artifacts.ts

Implement AssetManager that handles (un)delegation / reward distribution / slashing in governance token.

feat(contracts): implement AssetManager

---

packages/contracts/deployments/sepolia/Colosseum.json

This is an artifact of Colosseum contract upgraded for v1.4.0 on Kroma sepolia.

chore: update colosseum artifact for Kroma sepolia v1.4.0

---

kroma-validator/l2_output_submitter.go

When validator does not have enough deposit, it retries checking it continuously every 1 second. It results in too many request to L1 RPC, so changed not to retry in that case. If the validator is selected as a priority validator or in public round, it fails to submit a transaction due to gas estimation failure.

feat(validator): improve retry loop when validator has not enough deposit

---

packages/contracts/contracts/L1/ValidatorManager.sol
packages/contracts/contracts/L1/interfaces/IValidatorManager.sol

Separated jail period. Slightly revised a jail period calculation logic, to reflect an edge case that the non-submissions penalty and slashing penalty intercept.

feat(contracts): separate jail period

---

packages/contracts/contracts/L1/AssetManager.sol
packages/contracts/contracts/L1/interfaces/IAssetManager.sol

I will separate into several PRs for implementation of undelegation KRO, KGH, and KGH batch.

feat(contracts): implement 1-step undelegation of KRO

---

packages/contracts/contracts/L1/AssetManager.sol
packages/contracts/contracts/L1/interfaces/IAssetManager.sol

Added withdraw method for the validator.
This should be merged after #350

feat(contracts): add withdraw method for validator

---

packages/contracts/contracts/test/AssetManager.t.sol

Tested all added tests passed. You can check it by commenting `ValidatorManager` tests.

test(contracts): add `AssetManager` tests

---

nx.json

feat(nx-cloud): setup nx cloud workspace 
This commit sets up Nx Cloud for your Nx workspace, enabling distributed caching and the Nx Cloud GitHub integration for fast CI and improved developer experience.
You can access your Nx Cloud workspace by going to 
https://cloud.nx.app/orgs/672d775fe7535d520b298d46/workspaces/672d7b30b76a0e014484fab5
**Note:** This commit attempts to maintain formatting of the nx.json file, however you may need to correct formatting by running an nx format command and committing the changes.

feat: setup nx workspace

---

op-e2e/actions/kromampt_fork_test.go
op-e2e/actions/l2_sequencer.go

Added a test that checks if Kroma MPT upgrade transactions are executed in a correct way.

test(e2e): add a test for Kroma MPT upgrade transactions

---

kroma-bindings/bindings/registry.go
kroma-validator/config.go
packages/core-utils/src/kroma/deposit-transaction.ts

chore: fix some typos in comment
