kroma-network/kroma

components/validator/validator.go

validator hits cpu usage 100% because select statement in Validator.loop() doesn't do what we expect. This should sleep and wake up at every tick.

fix(validator): avoid infinite polling

---

components/batcher/batcher.go

This commit fixes the issue of not retrying when encountering errors during the creation of batch submission transaction.
Resolves: #5

fix(batcher): fix issue of not retrying failed batch tx before sending

---

packages/contracts/contracts/test/SafeCall.t.sol

forge-std using deterministic addresses.
When a deterministic deployment address is injected in forge test, the problem occures. 
So, try to avoid deterministic deployment address in forge test.
Fixes #7

test(contracts): avoid deterministic address

---

Makefile

The Makefile is modified to set the versions of the binaries using git tag. 
The versions are managed using git tag and GitHub release, and the version of the binaries is set to the tag associated with the commit.

chore: inject git tag as a version

---

Makefile
components/batcher/cmd/main.go
components/node/cmd/main.go
components/node/cmd/stateviz/main.go
components/node/version/version.go
components/validator/cmd/main.go

This commit contains changes that unify the version format to `{version}-{commit}`

build: unify version format to {version}-{commit}

---

.github/workflows/ci.yml
.github/workflows/test.yml

Exclude unpredictable behavior due to the parallel environment during e2e test operation. 
Related #9, #10

ci: add disable parallel option in e2e test

---

bindings/ast/canonicalize_test.go
bindings/hardhat/hardhat_test.go
bindings/hardhat/types.go
bindings/predeploys/addresses_test.go
components/node/eth/account_proof.go
components/node/eth/ssz_test.go
components/node/p2p/rpc_api.go
components/node/rollup/derive/frame_test.go
components/node/withdrawals/proof.go

There are some unsorted import statements, so I sorted them using [`goimports-reviser`](https://github.com/incu6us/goimports-reviser).
```bash
> goimports-reviser -rm-unused ./...
```
Currently, `goimports` do not sort import statements consistently (it is well-known issue: https://github.com/golang/go/issues/20818).
There are many other alternatives, and I tried to use `goimports-reviser` since it works well as we desired and they also have linter for sorting import statements (we can add linter to CI in the future as well). 
FYI, you can configure `goimports-reviser` in IntelliJ as described [here](https://github.com/incu6us/goimports-reviser#example-to-configure-it-with-jetbrains-ides-via-file-watcher-plugin).

chore: sort import statements

---

.github/workflows/ci.yml
.github/workflows/test.yml

we will maintain `self-hosting` for the time being to improve the issue of failed CI due to limited pipeline performance

chore: change git action runner to selfhost

---

.github/workflows/ci.yml
.github/workflows/test.yml

I have been using self-hosting to utilize more computing resources than the default specifications of GitHub Actions when running actions. 
However, I now have the option to use `larger runners`, so I'm switching to that.
> Additionally, we would like to lock/freeze the nightly version.

ci: change github action runner host

---

.github/workflows/ci.yml
.github/workflows/test.yml

change the policy to differentiate commits that are merged into the dev branch by tagging them in the docker image
also, the previously used release version is no longer available, so it is being replaced with a compatible alternative version.

ci: change dev tag name

---

specs/derivation.md
specs/glossary.md

chore: fix typos in specs

---

components/validator/challenger.go

Challenger needs to submit valid output to replace invalid output with when proving fault. Since the challenger have submitted destination output root before, fixed it.
Related #19

fix(validator): modify output to replace with when proving fault

---

components/validator/challenger.go
components/validator/guardian.go
components/validator/l2_output_submitter.go
components/validator/validator.go
e2e/actions/l2_challenger.go
e2e/actions/l2_validator.go

Fixed the validator component could not be restarted.
To do this, I modified each function to inject context as a parameter.

fix(validator): close channel and context when Stop() called

---

components/validator/challenger.go
e2e/actions/l2_challenger.go
e2e/actions/l2_challenger_test.go

When asserter timeout, skip finding fault position since the same segments have been stored in colosseum.

fix(validator): skip finding fault position in asserter timeout

---

components/validator/challenger.go

Output with proof is required when proving fault.

fix(challenger): fetch output with proof when proving fault

---

components/validator/challenger.go

To verify the state of withdrawal account, dst merkle proof is required.

fix(challenger): change the public input proof of dst output, not src

---

components/validator/challenger.go

MerkleProof fails because of the difference between the ABI encoding of uint types and bytes types.

fix(validator): fix incorrect encoding of L2ToL1MessagePasser balance

---

components/validator/challenger.go
components/validator/config.go
components/validator/guardian.go
packages/contracts/contracts/L1/Colosseum.sol
packages/contracts/contracts/libraries/NodeReader.sol

- Changed to use copy of `*big.Int` type output index when handling output submitted event.
- Changed to fetch proof and pair of destination block number.
- During creating validator config, parse security council address only when guardian is enabled. (if the config is not set, `ParseAddress` throws invalid address error)
- Fixed minor typos

fix(validator): fix several bugs related to challenger

---

components/validator/challenger.go

The `c.checkpoint` was validated twice unnecessarily. 
Let the `c.checkpoint` be validated once.

perf(challenger): remove unnecessary output validation

---

components/validator/challenger.go
e2e/actions/l2_challenger_test.go

When challenger handles each output, it should handle it without any delay. Therefore, changed to listen `ticker.C` in post-condition of for loop.
Also, during challenge handling, the same logic is applied.

perf(validator): remove delay of output handling

---

specs/challenge.md

Update the specs document that is not reflecting previous code changes.
Related #76

docs(validator): validate withdrawal storage root against state root

---

components/validator/challenger.go
components/validator/config.go
components/validator/guardian.go
components/validator/l2_output_submitter.go
components/validator/validator.go
e2e/actions/l2_runtime.go
e2e/actions/l2_validator.go
e2e/actions/l2_validator_test.go
e2e/actions/user_test.go
e2e/setup.go
e2e/system_test.go
utils/service/txmgr/buffered_txmgr.go
utils/service/txmgr/cli.go
utils/service/txmgr/txmgr.go

Fixes the current way of not receiving a response to a transaction request. 
Improved the way we can check for receipt in a synchronous manner, rather than simply passing a transaction request and being done with it in an asynchronous manner.
And use this to efficiently improve the retry logic based on the validators' responses.
Fixes #93

perf(validator): handle errors of validator's transactions

---

components/node/rollup/driver/state.go

The issue where subsequent engine sync API functionalities do not work if an error occurs during the execution of the `BlockRefsWithStatus` function has been fixed.
If an error occurs during the execution of the `BlockRefsWithStatus` function in the node's state driver (for example, when trying to query a non-existing block), all subsequent functions of the state driver do not work.
As a result, the node cannot proceed with the derivation, and therefore the geth will not be able to keep up with the latest block.
Modified the `BlockRefsWithStatus` function in the state driver to always send a signal to the wait channel (`<- wait`) even when an error occurs.

fix(node): fix the engine sync api getting stuck

---

components/validator/guardian.go
components/validator/l2_output_submitter.go

When first turned on the validator node when the chain is already far along, the validator needs to sync all the L2 blocks before it can attempt to submit output. 
Therefore, changed to polling until sync is completed instead of waiting L2 block time for each block.

fix(validator): prevent validator unnecessary waiting

---

.github/workflows/ci.yml
.github/workflows/test.yml

We aren't using submodules in this project.
We believe that using tokens to get submodules in CI is now unnecessary.

ci: remove checkout submodules

---

packages/contracts/contracts/L1/ZKMerkleTrie.sol

This commit resolves two audit issues.
https://github.com/chainlight-io/2023-kroma-network-audit-issues-client/issues/5
https://github.com/chainlight-io/2023-kroma-network-audit-issues-client/issues/6
Issue KROMA-005 is clearly a critical issue on its face.
However, the vulnerability cannot be exploited because of the following piece of code below.
```solidity
if (currentNode.keyPreimage != bytes32(0)) {
// NOTE(chokobole): The comparison order is important, because in this setting,
// first condition is mostly evaluted to be true. When we're sure about
// database preimage, then we need to enable just one of check below!
require(
currentNode.keyPreimage == _key || currentNode.keyPreimage == key,
"ZKMerkleTrie: invalid key preimage"
);
}
```
Note that we're only checking if …

fix: fix vulnerabilities reported to ZKTRIE

---

components/node/rollup/derive/frame.go

Related [[KROMA-013] Typo in JSON Tag of Marshal Frame struct definition](https://github.com/chainlight-io/2023-kroma-network-audit-issues-client/issues/13) reported by theori audit.
Fix typo in the JSON Tag of a struct definition.

fix(node): fix typo in JSON Tag

---

packages/contracts/contracts/libraries/NodeReader.sol

Related https://github.com/chainlight-io/2023-kroma-network-audit-issues-client/issues/8
Depending on the number of parameters in _compressedFlags and _values, _valueHash may not hash even once. 
ex
```solidity
bytes32 valueHash = _valueHash(0, "hello world!")
// valueHash does not hashed. it is "hello world!"
```
Initially, we were going to verify that _compressedFlags is non-zero in _valueHash, but since it's a low-level function, it could be used for anything, so we decided to verify it when creating the leaf node.

fix: validate compressedFlags

---

components/batcher/batch_submitter.go
components/node/eth/heads.go
components/node/p2p/discovery.go
components/node/p2p/sync.go
components/node/rollup/driver/state.go
components/validator/guardian.go
components/validator/l2_output_submitter.go
utils/service/metrics/balance.go

Related [[KROMA-012] Incorrect usage of Context.WithTimeout may lead to resource leak](https://github.com/chainlight-io/2023-kroma-network-audit-issues-client/issues/12) reported by theori audit.
At this point, i don't see this as an issue in terms of code behavior, but automated management of context via defer is a pattern that avoids potential issues, so i've implemented it.

chore: improve usage of Context.WithTimeout

---

packages/contracts/contracts/L1/L2OutputOracle.sol

Related to [[KROMA-010] Nodes should be able to handle configuration changes of contracts](https://github.com/chainlight-io/2023-kroma-network-audit-issues-client/issues/10) reported by theori audit.
**NOTE:** need to update client code in near future to reflect changed `immutable` variables when changed.

chore(contracts): remove safely modified comment in `L2OutputOracle`

---

components/validator/guardian.go

If an output has already been deleted, there is no need to make a request to delete the output.
Let guardian skip the deleted output.

fix(validator): skip request deletion when output already been deleted

---

package.json
packages/common-ts/package.json
packages/contracts/package.json
packages/core-utils/package.json
packages/hardhat-deploy-config/package.json
packages/sdk/package.json

bump up npm packages to v1.0.0
See
- https://www.npmjs.com/package/@kroma-network/hardhat-deploy-config
- https://www.npmjs.com/package/@kroma-network/common-ts
- https://www.npmjs.com/package/@kroma-network/core-utils
- https://www.npmjs.com/package/@kroma-network/sdk
- https://www.npmjs.com/package/@kroma-network/contracts

chore: bump npm packages to v1.0.0

---

components/validator/l2_output_submitter.go
components/validator/validator.go
e2e/actions/l2_validator.go
e2e/setup.go
utils/service/txmgr/price_bump_test.go
utils/service/txmgr/txmgr.go
utils/service/txmgr/txmgr_test.go

Since we have dynamic gas usage in unbond and priority validator selection logic, it is hard to estimate exact gas usage. This leads to frequent transaction failures, so to avoid this, set the output submission gas limit `1.5 * estimated gas`.

feat(validator): add gas limit margin when submitting output

---

packages/contracts/contracts/L2/ValidatorRewardVault.sol
packages/contracts/contracts/universal/FeeVault.sol

Fixed error in build contracts: https://github.com/kroma-network/kroma/actions/runs/7162496625/job/19499546642.
I made the `_processWithdrawal` be virtural in `FeeVault.sol`, and overrode this in `ValidatorRewardVault.sol`.

chore(contracts): make `_processWithdrawal()` be virtual for overriding

---

op-node/p2p/gossip.go

Rename the block topic in gossip p2p, which was modified in the OP upstream, back to kroma.
This is to maintain backward compatibility for existing p2p nodes.

feat(node): set block topic to kroma (gossip)

---

Dockerfile

Fixed an issue with Alpine images not having the desired multiplatform compatibility behavior.
Specify multiplatform in docker build.

build: specify multiplatform in docker build

---

op-service/sources/types.go

This is the same PR with #247, but only for release `v1.2.0-rc.2`.
`v1.2.0-rc.2` will be released on `release/v1.2.0-base` branch.

fix: add blob related fields to rpc header

---

op-service/sources/types.go

It is required to be compatible with Dencun L1.

feat: add 4844 fields to `rpcHeader`

---

kroma-validator/challenge/fetcher.go

With a new version of [kroma-prover](https://github.com/kroma-network/kroma-prover/releases/tag/v0.1.5-rc.1), `proofType` is not used anymore for generating ZK proof, so I removed it.

feat: remove proof type arg of prove json rpc

---

kroma-validator/challenger.go
kroma-validator/guardian.go

When using `syncStatus.CurrentL1` instead of `syncStatus.HeadL1`, it is impossible to scan between `CurrentL1` and `HeadL1`. If an asserter was off when a challenge was created, the asserter would not be able to react when turned on right after the event occurred. Guardian could also have the same issue, so fixed it also.

fix(validator): change challenger and guardian to scan until head L1

---

packages/contracts/contracts/L1/AssetManager.sol
packages/contracts/contracts/L1/Colosseum.sol
packages/contracts/contracts/L1/ValidatorManager.sol
packages/contracts/contracts/L1/interfaces/IAssetManager.sol
packages/contracts/contracts/L1/interfaces/IValidatorManager.sol

Bond validator KRO during output submission and challenge creation.

feat(contracts): bond validator KRO

---

packages/contracts/contracts/L1/AssetManager.sol
packages/contracts/contracts/L1/interfaces/IAssetManager.sol

Implement `claimKghReward` function. Includes `_claimBoostedReward` which has `isCompounding` flag.

feat: implement claimKghReward function

---

packages/contracts/contracts/L1/AssetManager.sol
packages/contracts/contracts/L1/interfaces/IAssetManager.sol

Handling of boosted reward and 1 step undelegation will be covered in the following PR.
Will be merged after merging #347 and #348.

feat: remove KGH share and modify KGH delegation func

---

packages/contracts/contracts/L1/AssetManager.sol
packages/contracts/contracts/L1/Colosseum.sol
packages/contracts/contracts/L1/ValidatorManager.sol
packages/contracts/contracts/L1/interfaces/IValidatorManager.sol

Unbond validator KRO during output finalization and slashing.
Additionally, there is a point to consider related to challenge process. I wanna discuss about the way to handle it, which I implemented in 83f1908c1a3e5f01a6659dd6c28d61ca79ae43a1.
When a malicious challenger successfully proved fault due to a ZK bug, the asserter will be slashed and not have bond anymore. But after challenge dismissed by security council, the output submitter is reverted to the asserter and the asserter's asset will be tried to be unbonded when output being finalized. In that case, the asserter does not have bond since it has been slashed, so output finalization will be reverted.
I made a change to replace the output submitter to security council when dismissing challenge, and block proving fault when …

feat(contracts): unbond validator KRO

---

packages/contracts/contracts/L1/AssetManager.sol

Added transferFrom function and logic of adding validator and boosted reward at `increaseBalanceWithReward` function.
Must be merged after #351

feat(contracts): add transferFrom when increasing reward of vault

---

packages/contracts/contracts/L1/ValidatorManager.sol

Update validator reward calculation, by excluding base reward for validator from the total base reward and including it into `validatorReward`.
Must be merged after #351, #354

feat(contracts): update validator reward calculation

---

kroma-validator/cmd/README.md
kroma-validator/cmd/main.go
kroma-validator/cmd/validator/cmd.go
packages/contracts/contracts/L1/AssetManager.sol

Updated subcommands for the changed validator system v2. 
Also found a duplicated check at `depositToRegister` function in AssetManager, so removed it.

feat: change validator client subcommands

---

kroma-validator/challenger.go
kroma-validator/config.go
kroma-validator/l2_output_submitter.go
kroma-validator/metrics/metrics.go
kroma-validator/metrics/noop.go
op-e2e/actions/l2_validator.go
packages/contracts/contracts/L1/AssetManager.sol
packages/contracts/contracts/L1/interfaces/IAssetManager.sol

Moved termination index from config to each components (`l2_output_submitter` / `challenger`), and added a check for bond amount at validator system v2. For this purpose, I added a view function which returns the balance of validator excluding the bond at AssetManager contract.

feat: modify validator client for validator system V2

---

packages/contracts/contracts/L1/AssetManager.sol
packages/contracts/contracts/test/AssetManager.t.sol
packages/contracts/contracts/test/Colosseum.t.sol
packages/contracts/contracts/test/L2OutputOracle.t.sol

Modified some tests of `Colosseum` related to V2. Also fixed the logic that stores boosted reward in `AssetManager` to avoid divide by zero error.

test(contracts): modify `Colosseum` tests related to V2

---

packages/contracts/contracts/L1/AssetManager.sol
packages/contracts/contracts/test/CommonTest.t.sol
packages/contracts/contracts/test/ValidatorManager.t.sol

fixes tests for validator manager contract for validator system v2.

test: fix validator manager contract tests

---

kroma-chain-ops/genesis/testdata/test-deploy-config-full.json
kroma-validator/challenger.go
kroma-validator/l2_output_submitter.go
op-e2e/actions/l2_challenger.go
op-e2e/actions/l2_challenger_test.go
op-e2e/actions/l2_runtime.go
op-e2e/actions/l2_validator.go
op-e2e/actions/l2_validator_test.go
op-e2e/e2eutils/validator/validator.go
op-e2e/setup.go
op-e2e/system_test.go
packages/contracts/deploy-config/devnetL1-template.json

Modified e2e tests according to V2, and also changed output submitter to assert output submission condition before trying to submit the tx. 
This PR should pass the CI test.

test(validator): modify e2e tests related to V2

---

packages/contracts/src/deploy-utils.ts

There was a bug in [this change](https://github.com/kroma-network/kroma/commit/0e7487f3c7d24b4bfe7a5f526b3e3f624af61c40#diff-120093f03b10b9455e845a77c01950510e03c25c7133d79c3d1a3aed678c421c), so I fixed it. If the contract is not deployed newly, skip upgrading the proxy contract.

fix(contracts): not upgrade already deployed contract

---

op-batcher/batcher/channel_builder_test.go
op-node/rollup/derive/span_channel_out.go

This PR addresses an issue in the batcher where the checksum was not being included during the compression of rlp_spanbatches using zlib. The checksum is now correctly included in the compressed data.
This work originated from an investigation into a derivation failure observed in Kona, during which it was discovered that the checksum was missing in the compressed output.
Additionally, a related upstream PR [#10002](https://github.com/ethereum-optimism/optimism/pull/10002), primarily focused on optimization and refactoring, also resolved this checksum issue as part of its broader changes.

fix(batcher): include checksum in zlib-compressed channel encoding

---

op-e2e/system_test.go
op-e2e/tx_helper.go

Added a system test for `proveWithdrawal` after MPT transition.
The previous `SendDeposit` function has always been failing to get receipt from L2 even after the transition to MPT, which I think the deposit tx is yet to be included in L2. Instead of waiting for some random number of blocks, I revised the function to take `isKromaMPT` flag.

test(e2e): add system test on withdrawal after MPT transition

---

op-node/rollup/derive/kromampt_upgrade_transactions.go
op-node/rollup/derive/kromampt_upgrade_transactions_test.go

Increase the deployment gas limit value of the gasPriceOracle(MPT) contract included in the MPT upgrade. 
The actual gas consumption is around 1.2 million.

feat: increase deployment gas limit for GasPriceOracleMPT

---

op-node/rollup/driver/sequencer.go
op-node/rollup/driver/state.go

The CI failures in previous PRs were suspected to be caused by system performance degradation due to continuous log output from the migrator. 
To fix it, I added a delay 1 second before calling the next engine API when the migration is not completed.

feat: delay sequencer action if migration is not completed

---

op-e2e/migration_test.go
op-e2e/setup.go
op-e2e/system_test.go

Added the fee distribution test in Kroma MPT.
The setup for historical RPC node and other nodes are repeated in all tests for Kroma MPT, so I added a utility function and global variable to set up MPT environment in system config setup.

test(e2e): add fee distribution test in Kroma MPT

---

packages/contracts/foundry.toml

To verify deployed contracts, enable build info(esp metadata) in foundry settings.

feat(contracts): enable build info in foundry settings

---

op-batcher/batcher/channel_builder.go
op-batcher/batcher/channel_manager_test.go
op-node/node/node.go
op-node/rollup/types.go

Prevents KromaMPT block from being handled as unsafe payload over P2P. 
This ensures that nodes can continue the migration process, even if they receive a new unsafe payload from the sequencer before receiving the batch containing the KromaMPT parent block, allowing them to still process the safe attribute.

feat: ignore KromaMPT block payload

---

kroma-chain-ops/cmd/check-kroma-mpt/main.go

I noticed a small but confusing typo in the error message within the `checkL1BlockAddrAndData` function. The second check, which occurs *after* MPT, incorrectly states "before MPT" in its error message.
This PR fixes the error message to accurately reflect that the check happens *after* MPT.

chore: Fix incorrect error message in Update main.go

---

kroma-validator/validator.go

The `l.Error` method from the `log` package doesn't support the `%w` formatting verb. This causes `%w` to be logged as a literal string instead of wrapping the error. I've updated the code to use the correct formatting for logging errors with `log.Logger`. This ensures errors are logged properly without losing context.

fix: fix incorrect error logging format
